<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * Apply iqual settings to forms.
 */
function iqual_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  if (!empty($form['field_yoast_seo'])) {
    $config = \Drupal::config('iqual.settings');
    if ($config->get('hide_title_slug')) {
        $form['field_yoast_seo']['widget'][0]['yoast_seo']['#attached']['library'][] = "iqual/yoast_seo";
    }
  }
}

/**
 * Implements hook_preprocess_node_add_list().
 *
 * Remove add page links for defined content types.
 */
function iqual_preprocess_node_add_list(&$vars) {

  $config = \Drupal::config('iqual.settings');
  if ($config->get('hide_node_add_links')) {
    $contentTypesToRemmove = $config->get('hide_node_add_links');
  }

  foreach ($contentTypesToRemmove as $type) {
    unset($vars['content'][$type]);
    unset($vars['types'][$type]);
  }
}
