<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\language\Entity\ConfigurableLanguage;
/**
 * Apply iqual settings to forms.
 */
function iqual_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  if (!empty($form['field_yoast_seo'])) {
    $config = \Drupal::config('iqual.settings');
    if ($config->get('hide_title_slug')) {
        $form['field_yoast_seo']['widget'][0]['yoast_seo']['#attached']['library'][] = "iqual/yoast_seo";
    }
  }
}

/**
 * Implements hook_entity_type_alter().
 *
 * Extend Language config entity.
 */
function iqual_entity_type_alter(&$entity_types) {
  if (isset($entity_types['configurable_language'])) {
    $formHandlerClasses = $entity_types['configurable_language']->getHandlerClasses()['form'];
    $formHandlerClasses['default'] = 'Drupal\iqual\Form\LanguageEditForm';
    $formHandlerClasses['edit'] = 'Drupal\iqual\Form\LanguageEditForm';
    $entity_types['configurable_language']->setHandlerClass('form', $formHandlerClasses);
  }
}


/**
 * Implements hook_metatags_alter().
 *
 * Replace lang code with locale code in hreflang.
 */
function iqual_page_attachments_alter(array &$attachments) {
  foreach ($attachments['#attached']['html_head'] as $index => $attachment) {
    if (substr($attachment[1], 0, 21) == 'hreflang_per_language') {
      $languageCode = $attachment[0]['#attributes']['hreflang'];
      $languageEntity = ConfigurableLanguage::load($languageCode);
      $languageLocaleCode = FALSE;
      if ($languageEntity && $languageEntity->get('third_party_settings') && is_array($languageEntity->get('third_party_settings'))) {
        $languageThridPartySettings = $languageEntity->get('third_party_settings');
        if ($languageThridPartySettings && is_array($languageThridPartySettings)) {
          if (array_key_exists('iqual', $languageThridPartySettings) && is_array($languageThridPartySettings)) {
            if (array_key_exists('locale', $languageThridPartySettings['iqual'])) {
              $languageLocaleCode = $languageEntity->get('third_party_settings')['iqual']['locale'];
            }
          }
        }
      }
      if ($languageLocaleCode) {
        $attachments['#attached']['html_head'][$index][0]['#attributes']['hreflang'] = $languageLocaleCode;
      }
    }
  }

}
